// ─── Departments ─────────────────────────────────────────────────────

export const DEPARTMENTS: string[] = [
  'Executive',
  'Finance',
  'Engineering',
  'Human Resources',
  'Marketing',
  'Sales',
  'Product',
  'Operations',
  'Customer Success',
  'Legal',
  'IT',
  'Procurement',
  'Real Estate',
  'Customer Support',
  'Data Science',
  'Design',
  'Quality Assurance',
  'DevOps',
  'Research & Development',
  'Business Development',
  'Strategy',
  'Compliance',
  'Administration',
  'Other',
];

// ─── Locations ───────────────────────────────────────────────────────

export const LOCATIONS: string[] = [
  'New York',
  'San Francisco',
  'London',
  'Chicago',
  'Austin',
  'Seattle',
  'Boston',
  'Los Angeles',
  'Denver',
  'Atlanta',
  'Miami',
  'Dallas',
  'Phoenix',
  'Portland',
  'Nashville',
  'Berlin',
  'Paris',
  'Tokyo',
  'Singapore',
  'Sydney',
  'Toronto',
  'Dubai',
  'Mumbai',
  'Bangalore',
  'Shanghai',
  'Other',
];
